name: Build

on:
  push:
    branches: [ master ]
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go: ["oldstable", "stable"]
        os: [ubuntu-latest]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Check out into the Go module directory
        uses: actions/checkout@v7

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -ldflags="-s -w" -v -o ../../build/tcb
        working-directory: cmd/bot

      - name: Test
        run: go test -v ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: tcb-${{ matrix.go }}-${{ matrix.os }}
          path: build/tcb
