name: Lint

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.16, 1.17]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: ${{ matrix.go }}

      - name: Check out into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Lint the code
        uses: golangci/golangci-lint-action@v2.5.2
        #with:
          #version: v1.29
